# Generated by Django 3.1.2 on 2022-03-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='no_of_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='total_rating',
            field=models.IntegerField(null=True),
        ),
    ]
